jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install flake8
      run: pip install flake8

    - name: Run linting
      run: flake8 .
      
    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: pytest
